"use client";

import { useEffect, useRef, useState } from "react";

const AGE_GATE_STORAGE_KEY = "presidential-age-gate-v2-approved";

export function AgeGate({ children, siteName }: Readonly<{ children: React.ReactNode; siteName: string }>) {
  const [approved, setApproved] = useState(false);
  const [declined, setDeclined] = useState(false);
  const enterRef = useRef<HTMLButtonElement>(null);
  useEffect(() => { try { setApproved(window.localStorage.getItem(AGE_GATE_STORAGE_KEY) === "approved"); } catch {} }, []);
  useEffect(() => { if (approved) return; const previousOverflow = document.body.style.overflow; document.body.style.overflow = "hidden"; return () => { document.body.style.overflow = previousOverflow; }; }, [approved]);
  useEffect(() => { if (!approved && !declined) enterRef.current?.focus(); }, [approved, declined]);
  const enter = () => { try { window.localStorage.setItem(AGE_GATE_STORAGE_KEY, "approved"); } catch {} setApproved(true); };
  return <>{children}{!approved ? <div aria-labelledby="age-gate-title" aria-modal="true" role="dialog" style={{ position: "fixed", inset: 0, zIndex: 10000, display: "grid", placeItems: "center", padding: "24px", background: "rgba(2, 9, 8, 0.98)", color: "#f7f8f7" }}><section style={{ width: "min(100%, 34rem)", border: "1px solid rgba(88, 195, 182, 0.72)", background: "#06100f", boxShadow: "0 28px 80px rgba(0, 0, 0, 0.5)", padding: "clamp(2rem, 6vw, 4rem)", textAlign: "center" }}><p style={{ margin: 0, color: "#58c3b6", fontFamily: "var(--font-clash-display, Arial, sans-serif)", fontSize: "0.78rem", fontWeight: 700, letterSpacing: "0.14em", textTransform: "uppercase" }}>{siteName}</p><h2 id="age-gate-title" style={{ margin: "18px 0 0", fontFamily: "var(--font-clash-display, Arial, sans-serif)", fontSize: "clamp(2.25rem, 8vw, 4.5rem)", fontWeight: 700, letterSpacing: "0.015em", lineHeight: 0.9, textTransform: "uppercase" }}>Are you 21 or older?</h2><p aria-live="polite" style={{ margin: "24px auto 0", maxWidth: "31rem", color: "#c9d8d3", fontSize: "1rem", lineHeight: 1.6 }}>{declined ? "You must be 21 or older to enter this website." : "This website contains cannabis-related information intended for adults 21+ where legal."}</p>{!declined ? <div style={{ display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: "12px", marginTop: "30px" }}><button onClick={enter} ref={enterRef} style={{ minHeight: "54px", border: "1px solid #58c3b6", background: "#58c3b6", color: "#06100f", cursor: "pointer", fontFamily: "var(--font-clash-display, Arial, sans-serif)", fontSize: "0.82rem", fontWeight: 700, letterSpacing: "0.07em", textTransform: "uppercase" }} type="button">Yes, enter</button><button onClick={() => setDeclined(true)} style={{ minHeight: "54px", border: "1px solid rgba(247, 248, 247, 0.5)", background: "transparent", color: "#f7f8f7", cursor: "pointer", fontFamily: "var(--font-clash-display, Arial, sans-serif)", fontSize: "0.82rem", fontWeight: 700, letterSpacing: "0.07em", textTransform: "uppercase" }} type="button">No, I am not</button></div> : <button onClick={() => setDeclined(false)} style={{ minHeight: "48px", marginTop: "30px", border: "1px solid #58c3b6", background: "transparent", color: "#58c3b6", cursor: "pointer", fontFamily: "var(--font-clash-display, Arial, sans-serif)", fontSize: "0.78rem", fontWeight: 700, letterSpacing: "0.07em", padding: "0 22px", textTransform: "uppercase" }} type="button">Go back</button>}</section></div> : null}</>;
}
